### ISSUE TITLE
DMCA

### ISSUE THREAD

**Issue by mlodyskiny** [maxi-schaefer/Chronos-Nuker#6]
Hello, I'm parkie (Chronos CEO) the CEO of Chronos (parkie - The Chronos CEO), I am the CEO of Chronos and as The CEO of Chronos I wish to get this repository removed, as I'm the CEO of Chronos.

Sincerely, parkie (CEO of Chronos).

**Comment by wiktorwiktor11** [comment]
are u the ceo of chronos??

**Comment by mlodyskiny** [comment]
Yes, as parkie (The CEO of Chronos) I can 100% assure you (as the CEO of Chronos) that I am the CEO of Chronos.

Sincerely, The CEO of Chronos - parkie (CEO of Chronos).

**Comment by wiktorwiktor11** [comment]
so u could say u are the ceo of chronos, right?

**Comment by mlodyskiny** [comment]
Yes, as parkie (The CEO of Chronos) I can 100% assure you (as the CEO of Chronos) that I am the CEO of Chronos.

Sincerely, The CEO of Chronos - parkie (CEO of Chronos).

**Comment by wiktorwiktor11** [comment]
Yes, as wiks (A Member of Chronos) I can 100% assure you (A Member of Chronos) that I am the A Member of Chronos.

Sincerely, A Member of Chronos - wiks (A Member of Chronos).
